import { Toaster } from "@/components/ui/sonner";
import { ThemeProvider } from "@/providers/theme-provider";
import { aqua, inter } from "@/styles/fonts";
import "@/styles/globals.css";
import { ViewTransitions } from "next-view-transitions";
import NextTopLoader from "nextjs-toploader";

import type { Metadata } from "next";

export const metadata: Metadata = {
	title: {
		template: "%s | Aquasense",
		default: "Aquasense",
	},
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<ViewTransitions>
			<html lang="pt-BR" suppressHydrationWarning>
				<body className={`${inter.variable} ${aqua.variable}`}>
					<ThemeProvider attribute="class" defaultTheme="system" enableSystem>
						<NextTopLoader color="#00B0EA" />

						{children}

						<Toaster />
					</ThemeProvider>
				</body>
			</html>
		</ViewTransitions>
	);
}
